### PR TITLE
Add event details to Event

### PR DESCRIPTION
**Pull request by kroesctrl**

### CODE REVIEW

**Review by jboon — APPROVED** [review]

**Review by harrymiddelburgetall — APPROVED** [review]

**Review by carlogeenen — APPROVED** [review]

**Review by smvdheijden — APPROVED** [review]

**Comment by kroesctrl** [comment]
retest this please

**Comment by kroesctrl** [comment]
retest this please

**Comment by kroesctrl** [comment]
retest this please

**Comment by kroesctrl** [comment]
retest this please

**Comment by Marcel-Jansen** [comment]
retest this please

**Comment by Marcel-Jansen** [comment]
retest this please

**Comment by Marcel-Jansen** [comment]
retest this please

**Comment by Marcel-Jansen** [comment]
retest this please

**Comment by kroesctrl** [comment]
Nightly: https://ci.opensmartgridplatform.org/view/Nightly/job/OSGP_open-smart-grid-platform_nightly/1162/

**Comment by kroesctrl** [comment]
Nightly is geslaagd

**Review by smvdheijden — APPROVED** [review]

**Pull request merged**
