### PR TITLE
spring-boot-version-upgrade-to-3.3.5

### PR DESCRIPTION
**Pull request by harrymiddelburgetall**
Upgrade of spring boot to version 3.3.5 required a change inlogback configuration.

### CODE REVIEW

**Comment by harrymiddelburgetall** [comment]
upgrading issues

**Comment by harrymiddelburgetall** [comment]
upgrading issues solved

**Comment by harrymiddelburgetall** [comment]
⏳ https://jenkins.fdp.osgp.cloud/view/SMHE-cucumber/job/gxf-smhe-cucumber-build/308/

**Comment by harrymiddelburgetall** [comment]
✔ https://jenkins.fdp.osgp.cloud/view/SMHE-cucumber/job/gxf-smhe-cucumber-build/309/

**Review by natasja-n — APPROVED** [review]

**Pull request merged**
