### PR TITLE
Bit error rate can be a number in class 47, version 2 and not a enum

### PR DESCRIPTION
**Pull request by kroesctrl**
Bit error rate can be a number in class 47, version 2 and not a enum

### CODE REVIEW

**Comment by kroesctrl** [comment]
https://jenkins.fdp.osgp.cloud/view/SMHE-cucumber/job/gxf-smhe-cucumber-build/136/

**Comment by kroesctrl** [comment]
https://jenkins.fdp.osgp.cloud/view/SMHE-cucumber/job/gxf-smhe-cucumber-build/138/

**Comment by kroesctrl** [comment]
https://jenkins.fdp.osgp.cloud/view/SMHE-cucumber/job/gxf-smhe-cucumber-build/139/

**Review by abolder — APPROVED** [review]

**Comment by kroesctrl** [comment]
https://jenkins.fdp.osgp.cloud/view/SMHE-cucumber/job/gxf-smhe-cucumber-build/141/

**Review by natasja-n — APPROVED** [review]

**Pull request merged**
