### PR TITLE
SMHE-1311: no logging for artemis broker url

### PR DESCRIPTION
**Pull request by abolder**
Signed-off-by: Andre Bolder <andre.bolder@alliander.com>

### CODE REVIEW

**Comment by abolder** [comment]
pre-nightly build : https://jenkins.fdp.osgp.cloud/view/SMHE-cucumber/job/gxf-smhe-cucumber-build/35/

**Comment by abolder** [comment]
Nieuwe pre-nightly https://jenkins.fdp.osgp.cloud/view/SMHE-cucumber/job/gxf-smhe-cucumber-build/36/

**Review by harrymiddelburgetall — APPROVED** [review]
Can't we just skip the password from

**Comment by abolder** [comment]
https://jenkins.fdp.osgp.cloud/view/SMHE-cucumber/job/gxf-smhe-cucumber-build/37/

**Review by Marcel-Jansen — APPROVED** [review]

**Pull request merged**
